electricity: "#3e89f4"
heat_low_decentral: "#f46e42"
heat_low_central: "#f4c842"
heat_med: "#d936f4"
heat_high: "#f48c42"
residual_waste: "#9b42f4"
biomass_solid: "#8b5a2b"
biomass_gas: "#4caf50"
h2: "#42aff4"

electricity-demand_hh: "#3e89f4"
electricity-demand_cts: "#426ef4"
electricity-demand_mob: "#4254f4"
electricity-demand_ind: "#493ef4"
heat_low_central-demand_hh: "#f46e42"
heat_low_central-demand_cts: "#f46242"
heat_low_central-demand_ind: "#f45642"
heat_low_decentral-demand_hh: "#f4424e"
heat_low_decentral-demand_cts: "#f44262"
heat_low_decentral-demand_ind: "#f44276"
heat_med-demand_ind: "#d936f4"
heat_high-demand_ind: "#f48c42"
electricity-import: "#d32f2f"
biomass_solid-commodity: "#6b4226"
biomass_gas-commodity: "#388e3c"
residual_waste-commodity: "#af42f4"
h2-commodity: "#42cef4"
electricity-wind: "#1e88e5"
electricity-pv_ground: "#f4d142"
electricity-pv_agri_horizontal: "#f4c242"
electricity-pv_agri_vertical: "#f4b342"
electricity-pv_rooftop: "#f4a542"
heat_low_decentral-solarthermal_plant: "#f48a42"
biomass_solid-boiler_heat_med: "#795548"
biomass_solid-boiler_heat_high: "#5d4037"
electricity-boiler_heat_med: "#e53935"
electricity-boiler_heat_high: "#c62828"
h2-boiler_heat_med: "#b71c1c"
h2-boiler_heat_high: "#9b0000"
electricity-electrolyzer: "#42b3f4"
electricity-heatpump_central: "#f4d942"
electricity-heatpump_decentral: "#f4ed42"
electricity-heatpump_heat_med: "#c0f442"
biomass_solid-extchp_heat_med: "#8d6e63"
biomass_solid-extchp_heat_high: "#6d4c41"
biomass_gas-extchp_heat_med: "#2e7d32"
biomass_gas-extchp_heat_high: "#1b5e20"
h2-extchp_heat_high: "#42f1f4"
residual_waste-extchp_heat_high: "#42d4f4"
residual_waste-extchp_heat_low_central: "#42b7f4"
biomass_solid-bpchp_heat_low_decentral: "#a1887f"
biomass_solid-bpchp_heat_low_central: "#8d6e63"
biomass_gas-bpchp_heat_low_decentral: "#66bb6a"
biomass_gas-bpchp_heat_low_central: "#43a047"
heat_low_decentral-storage: "#f47f41"
electricity-small_battery_storage: "#ec407a"
electricity-large_battery_storage: "#d81b60"
h2-export: "#8c41f4"
electricity-export: "#ef5350"
