electricity: "#3e89f4"
heat_low_decentral: "#f46e42"
heat_low_central: "#f4c842"
heat_med: "#8bf442"
heat_high: "#42f4ce"
residual_waste: "#9b42f4"
biomass_solid: "#f442aa"
biomass_gas: "#f4a142"
h2: "#42aff4"

electricity-demand_hh: "#3e89f4"
electricity-demand_cts: "#426ef4"
electricity-demand-mob: "#4254f4"
electricity-demand_ind: "#493ef4"
heat_low_central-demand_hh: "#f46e42"
heat_low_central_demand_cts: "#f46242"
heat_low_central_demand_ind: "#f45642"
heat_low_decentral-demand_hh: "#f4424e"
heat_low_decentral_demand_cts: "#f44262"
heat_low_decentral_demand_ind: "#f44276"
heat_med-demand_ind: "#8bf442"
heat_high-demand_ind: "#42f49b"
import-electricity: "#427ff4"
commodity_biomass_solid: "#f44188"
commodity_biomass_gas: "#f49b42"
commodity_residual_waste: "#af42f4"
commodity-h2: "#42cef4"
electricity-wind: "#6a89f4"
electricity-pv_ground: "#4278f4"
electricity-pv_agri: "#425df4"
electricity-pv_rooftop: "#4239f4"
heat_low_decentral_solarthermal_plant: "#f48a42"
heat_low_decentral_geothermal_plant: "#f47e42"
biomass_solid_boiler_heat_med: "#e642f4"
biomass_solid_boiler_heat_high: "#c642f4"
electricity_boiler_heat_med: "#a642f4"
electricity_boiler_heat_high: "#8442f4"
h2_boiler_heat_med: "#6242f4"
h2_boiler_heat_high: "#424af4"
electricity_electrolyzer: "#42b3f4"
electricity-heatpump_heat_low_central: "#f4d942"
electricity-heatpump_heat_low_decentral: "#f4ed42"
electricity-heatpump_heat_med: "#c0f442"
biomass_solid_extchp_heat_low_decentral: "#e142f4"
biomass_solid_extchp_heat_low_central: "#d142f4"
biomass_solid_extchp_heat_med: "#b142f4"
biomass_solid_extchp_heat_high: "#9142f4"
biomass_gas_extchp_heat_low_decentral: "#7142f4"
biomass_gas_extchp_heat_low_central: "#5142f4"
biomass_gas_extchp_heat_med: "#3142f4"
biomass_gas_extchp_heat_high: "#1142f4"
h2_extchp_heat_high: "#42f1f4"
residual_waste_extchp_heat_high: "#42d4f4"
residual_waste_extchp_heat_low_central: "#42b7f4"
biomass_solid_bpchp_heat_low_decentral: "#f441ca"
biomass_solid_bpchp_heat_low_central: "#f441dc"
biomass_solid_bpchp_heat_med: "#f441ee"
biomass_gas_bpchp_heat_low_decentral: "#f4c241"
biomass_gas_bpchp_heat_low_central: "#f4af41"
biomass_gas_bpchp_heat_med: "#f49c41"
heat_low_decentral_storage: "#f47f41"
electricity_storage_battery: "#41d6f4"
h2-export: "#41f4ca"
