
load: {
  "electricity-demand_hh-profile": {
      "dataset": "demand_electricity_region",
      "file": "demand_hh_power_timeseries.csv",
  },
  "electricity-demand_cts-profile": {
    "dataset": "demand_electricity_region",
    "file": "demand_cts_power_timeseries.csv",
  },
  "electricity-demand_mob-profile": {
    "dataset": "renewable_feedin",
    "file": "pv_feedin_timeseries.csv",
  },
  "electricity-demand_ind-profile": {
    "dataset": "demand_electricity_region",
    "file": "demand_ind_power_timeseries.csv",
  },
  "heat_low_central-demand_hh-profile": {
    "dataset": "demand_heat_region",
    "file": "demand_hh_heat_timeseries.csv",
  },
  "heat_low_central-demand_cts-profile": {
    "dataset": "demand_heat_region",
    "file": "demand_cts_heat_timeseries.csv",
  },
  "heat_low_central-demand_ind-profile": {
    "dataset": "demand_heat_region",
    "file": "demand_ind_heat_timeseries.csv",
  },
  "heat_low_decentral-demand_hh-profile": {
    "dataset": "demand_heat_region",
    "file": "demand_hh_heat_timeseries.csv",
  },
  "heat_low_decentral-demand_cts-profile": {
    "dataset": "demand_heat_region",
    "file": "demand_cts_heat_timeseries.csv",
  },
  "heat_low_decentral-demand_ind-profile": {
    "dataset": "demand_heat_region",
    "file": "demand_ind_heat_timeseries.csv",
  },
  "heat_med-demand_ind-profile": {
    "dataset": "demand_heat_ind_med_high",
    "file": "demand_ind_heat_med_timeseries.csv",
  },
  "heat_high-demand_ind-profile": {
    "dataset": "demand_heat_ind_med_high",
    "file": "demand_ind_heat_high_timeseries.csv",
  }
}

feedin: {
  "electricity-wind-profile": {
    "dataset": "renewable_feedin",
    "file": "wind_feedin_timeseries.csv",
  },
  "electricity-pv_ground-profile": {
    "dataset": "renewable_feedin",
    "file": "pv_feedin_timeseries.csv",
  },
  "electricity-pv_agri_horizontal-profile": {
    "dataset": "renewable_feedin",
    "file": "pv_feedin_timeseries.csv",
  },
  "electricity-pv_agri_vertical-profile": {
    "dataset": "renewable_feedin",
    "file": "pv_feedin_timeseries.csv",
  },
  "electricity-pv_rooftop-profile": {
    "dataset": "renewable_feedin",
    "file": "pv_feedin_timeseries.csv",
  },
  "heat_low_decentral-solarthermal_plant-profile": {
    "dataset": "renewable_feedin",
    "file": "st_feedin_timeseries.csv",
  },
  "heat_low_decentral-geothermal_plant-profile": {
    "dataset": "renewable_feedin",
    "file": "st_feedin_timeseries.csv",
  },
}

efficiencies: {
  "electricity-heatpump_central-profile": {
    "dataset": "heatpump_cop",
    "file": "heatpump_cop_timeseries.csv",
  },
  "electricity-heatpump_decentral-profile": {
    "dataset": "heatpump_cop",
    "file": "heatpump_cop_timeseries.csv",
  },
  "electricity-heatpump_heat_med-profile": {
    "dataset": "heatpump_cop_heat_med",
    "file": "heatpump_cop_heat_med_timeseries.csv",
  },
}
