##############################################################################
# This file holds configuration parameters for the creation of this dataset. #
##############################################################################

# Years for wind stats
wind_stats_operating_years:
    [
      2010,
      2015,
      2020,
      2024
    ]

# Years for PV ground stats
pv_ground_stats_operating_years:
    [
      2010,
      2015,
      2020,
      2024
    ]
