electricity: Strom
heat_low_decentral: Wärme (niedrig, dezentral)
heat_low_central: Wärme (niedrig, zentral)
heat_med: Wärme (mittel)
heat_high: Wärme (hoch)
residual_waste: Restmüll
biomass_solid: Feste Biomasse
biomass_gas: Biogas
h2: Wasserstoff

# Stromnachfragen
electricity-demand_hh: Stromnachfrage (Haushalte)
electricity-demand_cts: Stromnachfrage (Gewerbe, Handel, Dienstleistungen)
electricity-demand-mob: Stromnachfrage (Mobilität)
electricity-demand_ind: Stromnachfrage (Industrie)

# Wärme (niedrig) Nachfragen
heat_low_central-demand_hh: Wärme (niedrig, zentral) Nachfrage (Haushalte)
heat_low_central_demand_cts: Wärme (niedrig, zentral) Nachfrage (Gewerbe, Handel, Dienstleistungen)
heat_low_central_demand_ind: Wärme (niedrig, zentral) Nachfrage (Industrie)
heat_low_decentral-demand_hh: Wärme (niedrig, dezentral) Nachfrage (Haushalte)
heat_low_decentral_demand_cts: Wärme (niedrig, dezentral) Nachfrage (Gewerbe, Handel, Dienstleistungen)
heat_low_decentral_demand_ind: Wärme (niedrig, dezentral) Nachfrage (Industrie)

# Wärme (mittel) Nachfragen
heat_med-demand_ind: Wärme (mittel) Nachfrage (Industrie)

# Wärme (hoch) Nachfragen
heat_high-demand_ind: Wärme (hoch) Nachfrage (Industrie)

# Importe
import-electricity: Stromimport

# Rohstoffe
commodity_biomass_solid: Biomasse (fest)
commodity_biomass_gas: Biogas
commodity_residual_waste: Restmüll
commodity-h2: Wasserstoff

# Volatile
electricity-wind: Wind (onshore)
electricity-pv_ground: PV (Freifläche)
electricity-pv_agri: PV (Agrarflächen)
electricity-pv_rooftop: PV (Dachflächen)
heat_low_decentral_solarthermal_plant: Solarkollektor (dezentral)
heat_low_decentral_geothermal_plant: Geothermieanlage (dezentral)

# Umwandlung
biomass_solid_boiler_heat_med: Biomassekessel (fest, mittlere Wärme)
biomass_solid_boiler_heat_high: Biomassekessel (fest, hohe Wärme)
electricity_boiler_heat_med: Elektrokessel (mittlere Wärme)
electricity_boiler_heat_high: Elektrokessel (hohe Wärme)
h2_boiler_heat_med: Wasserstoffkessel (mittlere Wärme)
h2_boiler_heat_high: Wasserstoffkessel (hohe Wärme)
electricity_electrolyzer: Elektrolyseur

# Wärmepumpen
electricity-heatpump_heat_low_central: Wärmepumpe (niedrig, zentral)
electricity-heatpump_heat_low_decentral: Wärmepumpe (niedrig, dezentral)
electricity-heatpump_heat_med: Wärmepumpe (mittel)

# Entnahme-KWK (Kraft-Wärme-Kopplung)
biomass_solid_extchp_heat_low_decentral: Biomasse-KWK (fest, niedrig, dezentral)
biomass_solid_extchp_heat_low_central: Biomasse-KWK (fest, niedrig, zentral)
biomass_solid_extchp_heat_med: Biomasse-KWK (fest, mittel)
biomass_solid_extchp_heat_high: Biomasse-KWK (fest, hoch)
biomass_gas_extchp_heat_low_decentral: Biogas-KWK (niedrig, dezentral)
biomass_gas_extchp_heat_low_central: Biogas-KWK (niedrig, zentral)
biomass_gas_extchp_heat_med: Biogas-KWK (mittel)
biomass_gas_extchp_heat_high: Biogas-KWK (hoch)
h2_extchp_heat_high: Wasserstoff-KWK (hoch)
residual_waste_extchp_heat_high: Restmüll-KWK (hoch)
residual_waste_extchp_heat_low_central: Restmüll-KWK (niedrig, zentral)

# Gegendruck-KWK
biomass_solid_bpchp_heat_low_decentral: Biomasse-Gegendruck-KWK (fest, niedrig, dezentral)
biomass_solid_bpchp_heat_low_central: Biomasse-Gegendruck-KWK (fest, niedrig, zentral)
biomass_solid_bpchp_heat_med: Biomasse-Gegendruck-KWK (fest, mittel)
biomass_gas_bpchp_heat_low_decentral: Biogas-Gegendruck-KWK (niedrig, dezentral)
biomass_gas_bpchp_heat_low_central: Biogas-Gegendruck-KWK (niedrig, zentral)
biomass_gas_bpchp_heat_med: Biogas-Gegendruck-KWK (mittel)

# Speicher
heat_low_decentral_storage: Wärmespeicher (niedrig, dezentral)
electricity_storage_battery: Batteriespeicher (Strom)

# Überschuss
h2-export: Wasserstoffexport
