electricity: Electricity
heat_low_decentral: Heat (low, decentral)
heat_low_central: Heat (low, central)
heat_med: Heat (medium)
heat_high: Heat (high)
residual_waste: Residual waste
biomass_solid: Solid biomass
biomass_gas: Biogas
h2: Hydrogen

# Electricity demands
electricity-demand_hh: Electricity demand (households)
electricity-demand_cts: Electricity demand (commercial, trade, services)
electricity-demand-mob: Electricity demand (mobility)
electricity-demand_ind: Electricity demand (industry)
# Heat low demands
heat_low_central-demand_hh: Heat (low, central) demand (households)
heat_low_central_demand_cts: Heat (low, central) demand (commercial, trade, services)
heat_low_central_demand_ind: Heat (low, central) demand (industry)
heat_low_decentral-demand_hh: Heat (low, decentral) demand (households)
heat_low_decentral_demand_cts: Heat (low, decentral) demand (commercial, trade, services)
heat_low_decentral_demand_ind: Heat (low, decentral) demand (industry)

# Heat medium demands
heat_med-demand_ind: Heat (medium) demand (industry)

# Heat high demands
heat_high-demand_ind: Heat (high) demand (industry)

# Imports
import-electricity: Electricity import

# Commodities
commodity_biomass_solid: Biomass (solid)
commodity_biomass_gas: Biogas
commodity_residual_waste: Residual waste
commodity-h2: Hydrogen

# Volatile
electricity-wind: Wind (onshore)
electricity-pv_ground: PV (ground-mounted)
electricity-pv_agri: PV (agriculture)
electricity-pv_rooftop: PV (rooftop)
heat_low_decentral_solarthermal_plant: Solar thermal collector (decentral)
heat_low_decentral_geothermal_plant: Geothermal plant (decentral)

# Conversion
biomass_solid_boiler_heat_med: Solid biomass boiler (medium heat)
biomass_solid_boiler_heat_high: Solid biomass boiler (high heat)
electricity_boiler_heat_med: Electric boiler (medium heat)
electricity_boiler_heat_high: Electric boiler (high heat)
h2_boiler_heat_med: Hydrogen boiler (medium heat)
h2_boiler_heat_high: Hydrogen boiler (high heat)
electricity_electrolyzer: Electrolyzer

# Heat pumps
electricity-heatpump_heat_low_central: Heat pump (low, central)
electricity-heatpump_heat_low_decentral: Heat pump (low, decentral)
electricity-heatpump_heat_med: Heat pump (medium)

# Extraction CHP (combined heat and power)
biomass_solid_extchp_heat_low_decentral: Solid biomass extraction CHP (low, decentral)
biomass_solid_extchp_heat_low_central: Solid biomass extraction CHP (low, central)
biomass_solid_extchp_heat_med: Solid biomass extraction CHP (medium)
biomass_solid_extchp_heat_high: Solid biomass extraction CHP (high)
biomass_gas_extchp_heat_low_decentral: Biogas extraction CHP (low, decentral)
biomass_gas_extchp_heat_low_central: Biogas extraction CHP (low, central)
biomass_gas_extchp_heat_med: Biogas extraction CHP (medium)
biomass_gas_extchp_heat_high: Biogas extraction CHP (high)
h2_extchp_heat_high: Hydrogen extraction CHP (high)
residual_waste_extchp_heat_high: Residual waste extraction CHP (high)
residual_waste_extchp_heat_low_central: Residual waste extraction CHP (low, central)

# Backpressure CHP
biomass_solid_bpchp_heat_low_decentral: Solid biomass backpressure CHP (low, decentral)
biomass_solid_bpchp_heat_low_central: Solid biomass backpressure CHP (low, central)
biomass_solid_bpchp_heat_med: Solid biomass backpressure CHP (medium)
biomass_gas_bpchp_heat_low_decentral: Biogas backpressure CHP (low, decentral)
biomass_gas_bpchp_heat_low_central: Biogas backpressure CHP (low, central)
biomass_gas_bpchp_heat_med: Biogas backpressure CHP (medium)

# Storage
heat_low_decentral_storage: Heat storage (low, decentral)
electricity_storage_battery: Battery storage (electricity)

# Excess
h2-export: Hydrogen export
